ui: tape
capabilities:
  record-video: false
  video-upload-on-pass: false
  record-screenshots: false
browsers:
  - name: microsoftedge
    version: 20.10240..latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: chrome
    version: latest
  - name: ipad
    version: 9.0..latest
  - name: iphone
    version: 9.0..latest
